### ISSUE TITLE
Program stops with error "Error parsing data from deepl".

### ISSUE THREAD

**Issue by saurabhshri** [MatejMecka/captionsTranslator#3]
```
python3 captionsTranslator.py -i ../STshort.srt -o lol.srt -lf EN -lt ES
1 <i>Antes de Star Trek: Descubrimiento... </i>Necesito un equipo que me ayude.
2 Y eso te incluye a ti.
3 Acepto.
Error parsing data from deepl
```

What's happening there exactly - error is not descriptive enough to be rectified.

**Comment by MatejMecka** [comment]
The Program isn't exactly stopping but doesn't return that line. Why it happens is that when translating that line pydeepl returns `deepl.list index out of range` which means it cannot parse that data aka find the translated sentence. I'll see what I can do

**Comment by MatejMecka** [comment]
33b6b1c fixes this.
