### ISSUE TITLE
Text inside brackets is not being translated.

### ISSUE THREAD

**Issue by saurabhshri** [MatejMecka/captionsTranslator#4]
Input : 

```
8
00:00:20,955 --> 00:00:22,580
(yells)

9
00:00:24,830 --> 00:00:26,345
(roars)
```

Output : 

```
5
00:00:20, --> 00:00:26,
(yells)(roars)
```

Expected : 

```
5
00:00:20,955 --> 00:00:26,345
(schreit) (brüllt)
```

**Comment by MatejMecka** [comment]
For Spanish I get this:

https://screenshots.firefox.com/5nAxJJKH9XIZLbBp/www.deepl.com

But when I translate it to german that's the output

`(brüllt) (brüllt)`

The same thing is returned by deepl's site too.

So this is on deepl's side.

**Comment by saurabhshri** [comment]
Why would you send the text with bracket included?
