### ISSUE TITLE
Traceback - Deepl API changes

### ISSUE THREAD

**Issue by zoupzoup** [MatejMecka/captionsTranslator#5]
Hello !

I have correctly installed the requested dependencies and from this error message I don't understand what's going on... Could you help me, please :heart_eyes: 

CDE 

python captionsTranslator.py -i '/home/####/Bureau/captionsTranslator-master/sub/2_EN.srt' -o '/home/####/Bureau/captionsTranslator-master/sub/2_FR.srt' -lf EN -lt FR

Traceback (most recent call last):
  File "captionsTranslator.py", line 92, in <module>
    main()
  File "captionsTranslator.py", line 89, in main
    parsefiles(args.input_file, args.output_file, args.language_from, args.language_to)
  File "captionsTranslator.py", line 78, in parsefiles
    handleTranslations(tempFile.name, outputFile, languageFrom, languageTo)
  File "captionsTranslator.py", line 60, in handleTranslations
    translate(inp, out, laf, lat)
  File "captionsTranslator.py", line 22, in translate
    translationSentence = pydeepl.translate(linefromsub, languaget.upper(), languagef.upper())
  File "/usr/local/lib/python2.7/dist-packages/pydeepl/pydeepl.py", line 97, in translate
    raise TranslationError('DeepL call resulted in a unknown result.')
pydeepl.pydeepl.TranslationError: DeepL call resulted in a unknown result.

zoupzoup

**Comment by MatejMecka** [comment]
Hey there! Thanks for reporting this! I managed to reproduce it. It arrives from the deepl library. I'll try to fix it ASAP

**Comment by zoupzoup** [comment]
Thank you very much !!

**Comment by MatejMecka** [comment]
Hey there!

I identified the  issue and that is due to a change in Deepl's API. They released a new version and the old one deprecated. So there are 2 possible solutions.

1) Use the official one instead of scraping it.

- That requires the user paying for their subtitle files to be translated

2) Find another way to scrape the results 

- That would take more time and  also be on the watch for more breaking changes

**Comment by zoupzoup** [comment]
Hello !

Thank you for your answer, unfortunately I have neither the technical skills to help you nor a premium subscription. I think I understood that you have to subscribe to the "developer" package to get the API which is even more expensive because it counts the number of letters to translate....

There would probably be something to do in python to send requests via the classic interface and without subscription, but again I can't help you...

thank you very much for your quick answer,

Cordially,
Gildas.

Translated with www.DeepL.com/Translator

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
